---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.zirain.info
  resources:
  - ratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.zirain.info
  resources:
  - ratelimits/finalizers
  verbs:
  - update
- apiGroups:
  - policy.zirain.info
  resources:
  - ratelimits/status
  verbs:
  - get
  - patch
  - update
